export const photographyPrompts = [
  "Professional corporate headshot photography.",
  "Head and shoulders portrait.",
  "Subject facing camera.",
  "Natural upright posture.",
  "Camera positioned at eye level.",
  "85mm portrait lens.",
  "Moderate shallow depth of field.",
  "Sharp focus on both eyes.",
  "Soft studio key light.",
  "Subtle fill light.",
  "Natural facial shadows.",
  "Clean professional studio environment.",
  "Simple solid-color background.",
  "Natural skin texture.",
  "Realistic pores and fine facial detail.",
  "Natural hair texture.",
  "Accurate eye color.",
  "Neutral professional expression with a subtle natural smile.",
  "Photorealistic DSLR photography.",
  "Natural color science.",
  "True-to-life skin tones.",
  "No beauty-filter appearance.",
];
